"""Add weekend discount field to products table."""

print("🚀 Weekend Discount Migration")
print("=" * 50)
print()
print("This migration adds the 'weekend_discount_dkk' column to the products table.")
print()
print("Please run this SQL command in your database:")
print()
print("ALTER TABLE products ADD COLUMN weekend_discount_dkk DECIMAL(10, 2) DEFAULT NULL;")
print()
print("After running the SQL command:")
print("1. Restart your webapp")
print("2. Go to admin panel → Products → Edit a product")
print("3. You'll see the new 'Fuld weekend pris (Fre-Søn)' field")
print()
print("✅ Migration instructions provided!")